CREATE TABLESPACE PAYNET_S DATAFILE
  'D:\ORACLE\ORADATA\VPN4\PAYNET_S.DBF' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL;

CREATE TABLESPACE PAYNET_LOB DATAFILE
  'D:\ORACLE\ORADATA\VPN4\PAYNET_LOB.DBF' SIZE 48M AUTOEXTEND ON NEXT 48M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL;

CREATE TABLESPACE PAYNET_LOG DATAFILE
  'D:\ORACLE\ORADATA\VPN4\PAYNET_LOG.DBF' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL;


CREATE TABLE LOTTO.TS_CATEGORY
(
  CATEGORY_ID  NUMBER(10),
  NAME         VARCHAR2(255 BYTE),
  ACTIVE       CHAR(1 BYTE),
  CREATED_ON   DATE                             DEFAULT sysdate               NOT NULL
)
TABLESPACE PAYNET_S
LOGGING
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.TS_FIELD
(
  SERVICE_TYPE_ID  NUMBER(10),
  FIELD_NAME       VARCHAR2(20 BYTE),
  FIELD_LABEL      VARCHAR2(20 BYTE),
  FIELD_TYPE       VARCHAR2(11 BYTE),
  FIELD_SIZE       NUMBER(10),
  IS_REQUIRED      VARCHAR2(5 BYTE),
  ACTIVE           CHAR(1 BYTE),
  CREATED_ON       DATE                         DEFAULT sysdate               NOT NULL
)
TABLESPACE PAYNET_S
LOGGING
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.TS_PROVIDER
(
  PROVIDER_ID  NUMBER(10),
  CATEGORY_ID  NUMBER(10),
  NAME         VARCHAR2(255 BYTE),
  ACTIVE       CHAR(1 BYTE),
  CREATED_ON   DATE                             DEFAULT sysdate               NOT NULL
)
TABLESPACE PAYNET_S
LOGGING
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.TS_SERVICE
(
  SERVICE_ID       NUMBER(10),
  NAME             VARCHAR2(255 BYTE),
  PROVIDER_ID      NUMBER(10),
  CATEGORY_ID      NUMBER(10),
  SERVICE_TYPE_ID  NUMBER(10),
  ACTIVE           CHAR(1 BYTE),
  CHEQUE_INFO      VARCHAR2(2000 CHAR),
  CREATED_ON       DATE                         DEFAULT sysdate               NOT NULL,
  SERVICE_PRICE    NUMBER(14,4)
)
TABLESPACE PAYNET_S
LOGGING
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.TS_SERVICE_TYPE
(
  SERVICE_TYPE_ID  NUMBER(10),
  ACTIVE           CHAR(1 BYTE),
  CREATED_ON       DATE                         DEFAULT sysdate               NOT NULL
)
TABLESPACE PAYNET_S
LOGGING
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX LOTTO.PK_CATEGORY ON LOTTO.TS_CATEGORY
(CATEGORY_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LOTTO.PK_FIELD ON LOTTO.TS_FIELD
(FIELD_NAME, SERVICE_TYPE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LOTTO.PK_PROVIDER ON LOTTO.TS_PROVIDER
(PROVIDER_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LOTTO.PK_SERVICE ON LOTTO.TS_SERVICE
(SERVICE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LOTTO.PK_SERVICE_TYPE ON LOTTO.TS_SERVICE_TYPE
(SERVICE_TYPE_ID)
LOGGING
NOPARALLEL;


ALTER TABLE LOTTO.TS_CATEGORY ADD (
  CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID));


ALTER TABLE LOTTO.TS_FIELD ADD (
  CONSTRAINT PK_FIELD PRIMARY KEY (FIELD_NAME, SERVICE_TYPE_ID));


ALTER TABLE LOTTO.TS_PROVIDER ADD (
  CONSTRAINT PK_PROVIDER PRIMARY KEY (PROVIDER_ID));


ALTER TABLE LOTTO.TS_SERVICE ADD (
  CONSTRAINT PK_SERVICE PRIMARY KEY (SERVICE_ID));


ALTER TABLE LOTTO.TS_SERVICE_TYPE ADD (
  CONSTRAINT PK_SERVICE_TYPE PRIMARY KEY (SERVICE_TYPE_ID));


CREATE TABLE LOTTO.T_PAYMENT
(
  PAYMENT_ID          NUMBER                    NOT NULL,
  INTERNAL_CHEQUE_ID  VARCHAR2(20 BYTE),
  PAYNET_CHEQUE_ID    VARCHAR2(20 BYTE),
  STATE               CHAR(1 BYTE),
  SENT_ON             DATE,
  PROVIDER_ID         NUMBER,
  SERVICE_ID          NUMBER,
  SUMM                NUMBER(14,4),
  STATUS_CODE         NUMBER,
  URL                 VARCHAR2(2000 BYTE),
  ACTION_CODE         NUMBER,
  TERMINAL_ID         VARCHAR2(20 BYTE),
  REPORT_DATE         VARCHAR2(20 BYTE),
  SERVICE_PRICE       NUMBER(14,4),
  QUANTITY            NUMBER,
  TRANSACTION_ID      NUMBER,
  STATUS_TEXT         VARCHAR2(255 CHAR),
  XML_RESPONSE        BLOB
)
TABLESPACE PAYNET_LOG
LOGGING
LOB (XML_RESPONSE) STORE AS
      ( TABLESPACE  PAYNET_LOB
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
      )
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.T_PAYMENT_DETAIL
(
  PAYMENT_DETAIL_ID  NUMBER(19)                 NOT NULL,
  PAYMENT_ID         NUMBER(19),
  FIELD_NAME         VARCHAR2(255 BYTE),
  FIELD_VALUE        VARCHAR2(255 BYTE)
)
TABLESPACE PAYNET_LOG
LOGGING
NOCACHE
NOPARALLEL;


CREATE TABLE LOTTO.T_TRANSACTION
(
  TRANSACTION_ID    NUMBER(10)                  NOT NULL,
  PAYNET_CHEQUE     VARCHAR2(30 BYTE),
  TRANSACTION_DATE  DATE,
  STATUS_CODE       NUMBER(10),
  STATUS_TEXT       VARCHAR2(255 BYTE),
  RECEIPT_DETAILS   VARCHAR2(2000 BYTE),
  SUMMA             NUMBER(14,4),
  COMMISSION        NUMBER(14,4)
)
TABLESPACE PAYNET_LOG
LOGGING
NOCACHE
NOPARALLEL;


ALTER TABLE LOTTO.T_PAYMENT ADD (
  PRIMARY KEY (PAYMENT_ID)
    USING INDEX
    TABLESPACE SYSTEM);


ALTER TABLE LOTTO.T_PAYMENT_DETAIL ADD (
  PRIMARY KEY (PAYMENT_DETAIL_ID)
    USING INDEX
    TABLESPACE SYSTEM);


ALTER TABLE LOTTO.T_TRANSACTION ADD (
  PRIMARY KEY (TRANSACTION_ID)
    USING INDEX
    TABLESPACE SYSTEM);

