package cc;/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */
public interface ExampleConstants {

  int EOF = 0;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"a\"",
    "\"c\"",
    "\"b\"",
  };

}
